@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
REM Generated by Vivado on Mon Oct 03 09:56:35 +1100 2022
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: compile.bat
REM
REM ****************************************************************************
REM compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L axi_vip_v1_1_12 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_12 -L xilinx_vip -prj tb_microphone_sim_vlog.prj"
call xvlog  --incr --relax -L axi_vip_v1_1_12 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_12 -L xilinx_vip -prj tb_microphone_sim_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
REM compile VHDL design sources
echo "xvhdl --incr --relax -prj tb_microphone_sim_vhdl.prj"
call xvhdl  --incr --relax -prj tb_microphone_sim_vhdl.prj -log xvhdl.log
call type xvhdl.log >> compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
